// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.2
// source: protos/rastochnoy/rastoschnoy.proto

package rastochnoy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadWriteRastoshnoyDB33Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Offsett       *float64               `protobuf:"fixed64,3,opt,name=offsett,proto3,oneof" json:"offsett,omitempty"`
	Value         *float32               `protobuf:"fixed32,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastoshnoyDB33Item) Reset() {
	*x = ReadWriteRastoshnoyDB33Item{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastoshnoyDB33Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastoshnoyDB33Item) ProtoMessage() {}

func (x *ReadWriteRastoshnoyDB33Item) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastoshnoyDB33Item.ProtoReflect.Descriptor instead.
func (*ReadWriteRastoshnoyDB33Item) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{0}
}

func (x *ReadWriteRastoshnoyDB33Item) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ReadWriteRastoshnoyDB33Item) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ReadWriteRastoshnoyDB33Item) GetOffsett() float64 {
	if x != nil && x.Offsett != nil {
		return *x.Offsett
	}
	return 0
}

func (x *ReadWriteRastoshnoyDB33Item) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type ReadWriteRastochnoyDB33Res struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          []*ReadWriteRastoshnoyDB33Item `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastochnoyDB33Res) Reset() {
	*x = ReadWriteRastochnoyDB33Res{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastochnoyDB33Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastochnoyDB33Res) ProtoMessage() {}

func (x *ReadWriteRastochnoyDB33Res) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastochnoyDB33Res.ProtoReflect.Descriptor instead.
func (*ReadWriteRastochnoyDB33Res) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{1}
}

func (x *ReadWriteRastochnoyDB33Res) GetData() []*ReadWriteRastoshnoyDB33Item {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadWriteRastochnoyDB33Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastochnoyDB33Req) Reset() {
	*x = ReadWriteRastochnoyDB33Req{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastochnoyDB33Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastochnoyDB33Req) ProtoMessage() {}

func (x *ReadWriteRastochnoyDB33Req) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastochnoyDB33Req.ProtoReflect.Descriptor instead.
func (*ReadWriteRastochnoyDB33Req) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{2}
}

type WriteRastochnoydb33Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRastochnoydb33Res) Reset() {
	*x = WriteRastochnoydb33Res{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRastochnoydb33Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRastochnoydb33Res) ProtoMessage() {}

func (x *WriteRastochnoydb33Res) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRastochnoydb33Res.ProtoReflect.Descriptor instead.
func (*WriteRastochnoydb33Res) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRastochnoydb33Res) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRastochnoydb33Res) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WriteRastochnoydb33Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRastochnoydb33Req) Reset() {
	*x = WriteRastochnoydb33Req{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRastochnoydb33Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRastochnoydb33Req) ProtoMessage() {}

func (x *WriteRastochnoydb33Req) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRastochnoydb33Req.ProtoReflect.Descriptor instead.
func (*WriteRastochnoydb33Req) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRastochnoydb33Req) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRastochnoydb33Req) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WrtieRastochnoyDb37Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrtieRastochnoyDb37Req) Reset() {
	*x = WrtieRastochnoyDb37Req{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrtieRastochnoyDb37Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrtieRastochnoyDb37Req) ProtoMessage() {}

func (x *WrtieRastochnoyDb37Req) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrtieRastochnoyDb37Req.ProtoReflect.Descriptor instead.
func (*WrtieRastochnoyDb37Req) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{5}
}

func (x *WrtieRastochnoyDb37Req) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WrtieRastochnoyDb37Req) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type WrtieRastochnoyDb37Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrtieRastochnoyDb37Res) Reset() {
	*x = WrtieRastochnoyDb37Res{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrtieRastochnoyDb37Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrtieRastochnoyDb37Res) ProtoMessage() {}

func (x *WrtieRastochnoyDb37Res) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrtieRastochnoyDb37Res.ProtoReflect.Descriptor instead.
func (*WrtieRastochnoyDb37Res) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{6}
}

func (x *WrtieRastochnoyDb37Res) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadWriteRastochnoyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastochnoyReq) Reset() {
	*x = ReadWriteRastochnoyReq{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastochnoyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastochnoyReq) ProtoMessage() {}

func (x *ReadWriteRastochnoyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastochnoyReq.ProtoReflect.Descriptor instead.
func (*ReadWriteRastochnoyReq) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{7}
}

type ReadWriteRastoshnoyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Offsett       *float64               `protobuf:"fixed64,3,opt,name=offsett,proto3,oneof" json:"offsett,omitempty"`
	Value         *bool                  `protobuf:"varint,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastoshnoyItem) Reset() {
	*x = ReadWriteRastoshnoyItem{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastoshnoyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastoshnoyItem) ProtoMessage() {}

func (x *ReadWriteRastoshnoyItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastoshnoyItem.ProtoReflect.Descriptor instead.
func (*ReadWriteRastoshnoyItem) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{8}
}

func (x *ReadWriteRastoshnoyItem) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ReadWriteRastoshnoyItem) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ReadWriteRastoshnoyItem) GetOffsett() float64 {
	if x != nil && x.Offsett != nil {
		return *x.Offsett
	}
	return 0
}

func (x *ReadWriteRastoshnoyItem) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

type ReadWriteRastochnoyRes struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*ReadWriteRastoshnoyItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadWriteRastochnoyRes) Reset() {
	*x = ReadWriteRastochnoyRes{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadWriteRastochnoyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteRastochnoyRes) ProtoMessage() {}

func (x *ReadWriteRastochnoyRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteRastochnoyRes.ProtoReflect.Descriptor instead.
func (*ReadWriteRastochnoyRes) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{9}
}

func (x *ReadWriteRastochnoyRes) GetData() []*ReadWriteRastoshnoyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRastochnoyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRastochnoyReq) Reset() {
	*x = WriteRastochnoyReq{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRastochnoyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRastochnoyReq) ProtoMessage() {}

func (x *WriteRastochnoyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRastochnoyReq.ProtoReflect.Descriptor instead.
func (*WriteRastochnoyReq) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{10}
}

func (x *WriteRastochnoyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRastochnoyReq) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type WriteRastochnoyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRastochnoyRes) Reset() {
	*x = WriteRastochnoyRes{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRastochnoyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRastochnoyRes) ProtoMessage() {}

func (x *WriteRastochnoyRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRastochnoyRes.ProtoReflect.Descriptor instead.
func (*WriteRastochnoyRes) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{11}
}

func (x *WriteRastochnoyRes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRastochnoyRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRastochnoyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRastochnoyReq) Reset() {
	*x = ReadRastochnoyReq{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRastochnoyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRastochnoyReq) ProtoMessage() {}

func (x *ReadRastochnoyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRastochnoyReq.ProtoReflect.Descriptor instead.
func (*ReadRastochnoyReq) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{12}
}

type RastochnoyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`           // Masalan: "Out_Vibor_L"
	Offsett       *float64               `protobuf:"fixed64,3,opt,name=offsett,proto3,oneof" json:"offsett,omitempty"` // Masalan: 0.0
	Value         *bool                  `protobuf:"varint,4,opt,name=value,proto3,oneof" json:"value,omitempty"`      // Masalan: 1 yoki 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RastochnoyItem) Reset() {
	*x = RastochnoyItem{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RastochnoyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RastochnoyItem) ProtoMessage() {}

func (x *RastochnoyItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RastochnoyItem.ProtoReflect.Descriptor instead.
func (*RastochnoyItem) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{13}
}

func (x *RastochnoyItem) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RastochnoyItem) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *RastochnoyItem) GetOffsett() float64 {
	if x != nil && x.Offsett != nil {
		return *x.Offsett
	}
	return 0
}

func (x *RastochnoyItem) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

type ReadRastochnoyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RastochnoyItem      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRastochnoyRes) Reset() {
	*x = ReadRastochnoyRes{}
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRastochnoyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRastochnoyRes) ProtoMessage() {}

func (x *ReadRastochnoyRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rastochnoy_rastoschnoy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRastochnoyRes.ProtoReflect.Descriptor instead.
func (*ReadRastochnoyRes) Descriptor() ([]byte, []int) {
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP(), []int{14}
}

func (x *ReadRastochnoyRes) GetData() []*RastochnoyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protos_rastochnoy_rastoschnoy_proto protoreflect.FileDescriptor

const file_protos_rastochnoy_rastoschnoy_proto_rawDesc = "" +
	"\n" +
	"#protos/rastochnoy/rastoschnoy.proto\x12\n" +
	"rastochnoy\"\xa8\x01\n" +
	"\x1bReadWriteRastoshnoyDB33Item\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x1d\n" +
	"\aoffsett\x18\x03 \x01(\x01H\x02R\aoffsett\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\x02H\x03R\x05value\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_keyB\n" +
	"\n" +
	"\b_offsettB\b\n" +
	"\x06_value\"Y\n" +
	"\x1aReadWriteRastochnoyDB33Res\x12;\n" +
	"\x04data\x18\x01 \x03(\v2'.rastochnoy.ReadWriteRastoshnoyDB33ItemR\x04data\"\x1c\n" +
	"\x1aReadWriteRastochnoyDB33Req\"D\n" +
	"\x16WriteRastochnoydb33Res\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x16WriteRastochnoydb33Req\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"A\n" +
	"\x17WrtieRastochnoy_db37Req\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"3\n" +
	"\x17WrtieRastochnoy_db37Res\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x16ReadWriteRastochnoyReq\"\xa4\x01\n" +
	"\x17ReadWriteRastoshnoyItem\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x1d\n" +
	"\aoffsett\x18\x03 \x01(\x01H\x02R\aoffsett\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\bH\x03R\x05value\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_keyB\n" +
	"\n" +
	"\b_offsettB\b\n" +
	"\x06_value\"Q\n" +
	"\x16ReadWriteRastochnoyRes\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.rastochnoy.ReadWriteRastoshnoyItemR\x04data\"<\n" +
	"\x12WriteRastochnoyReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"@\n" +
	"\x12WriteRastochnoyRes\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ReadRastochnoyReq\"\x9b\x01\n" +
	"\x0eRastochnoyItem\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x1d\n" +
	"\aoffsett\x18\x03 \x01(\x01H\x02R\aoffsett\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\bH\x03R\x05value\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_keyB\n" +
	"\n" +
	"\b_offsettB\b\n" +
	"\x06_value\"C\n" +
	"\x11ReadRastochnoyRes\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.rastochnoy.RastochnoyItemR\x04data2\xba\x04\n" +
	"\n" +
	"Rastochnoy\x12Q\n" +
	"\x0fWriteRastochnoy\x12\x1e.rastochnoy.WriteRastochnoyReq\x1a\x1e.rastochnoy.WriteRastochnoyRes\x12]\n" +
	"\x13ReadWriteRastochnoy\x12\".rastochnoy.ReadWriteRastochnoyReq\x1a\".rastochnoy.ReadWriteRastochnoyRes\x12N\n" +
	"\x0eReadRastochnoy\x12\x1d.rastochnoy.ReadRastochnoyReq\x1a\x1d.rastochnoy.ReadRastochnoyRes\x12`\n" +
	"\x14WrtieRastochnoy_db37\x12#.rastochnoy.WrtieRastochnoy_db37Req\x1a#.rastochnoy.WrtieRastochnoy_db37Res\x12]\n" +
	"\x13WriteRastochnoyDB33\x12\".rastochnoy.WriteRastochnoydb33Req\x1a\".rastochnoy.WriteRastochnoydb33Res\x12i\n" +
	"\x17ReadWriteRastochnoyDB33\x12&.rastochnoy.ReadWriteRastochnoyDB33Req\x1a&.rastochnoy.ReadWriteRastochnoyDB33ResB\x15Z\x13genproto/rastochnoyb\x06proto3"

var (
	file_protos_rastochnoy_rastoschnoy_proto_rawDescOnce sync.Once
	file_protos_rastochnoy_rastoschnoy_proto_rawDescData []byte
)

func file_protos_rastochnoy_rastoschnoy_proto_rawDescGZIP() []byte {
	file_protos_rastochnoy_rastoschnoy_proto_rawDescOnce.Do(func() {
		file_protos_rastochnoy_rastoschnoy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_rastochnoy_rastoschnoy_proto_rawDesc), len(file_protos_rastochnoy_rastoschnoy_proto_rawDesc)))
	})
	return file_protos_rastochnoy_rastoschnoy_proto_rawDescData
}

var file_protos_rastochnoy_rastoschnoy_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_rastochnoy_rastoschnoy_proto_goTypes = []any{
	(*ReadWriteRastoshnoyDB33Item)(nil), // 0: rastochnoy.ReadWriteRastoshnoyDB33Item
	(*ReadWriteRastochnoyDB33Res)(nil),  // 1: rastochnoy.ReadWriteRastochnoyDB33Res
	(*ReadWriteRastochnoyDB33Req)(nil),  // 2: rastochnoy.ReadWriteRastochnoyDB33Req
	(*WriteRastochnoydb33Res)(nil),      // 3: rastochnoy.WriteRastochnoydb33Res
	(*WriteRastochnoydb33Req)(nil),      // 4: rastochnoy.WriteRastochnoydb33Req
	(*WrtieRastochnoyDb37Req)(nil),      // 5: rastochnoy.WrtieRastochnoy_db37Req
	(*WrtieRastochnoyDb37Res)(nil),      // 6: rastochnoy.WrtieRastochnoy_db37Res
	(*ReadWriteRastochnoyReq)(nil),      // 7: rastochnoy.ReadWriteRastochnoyReq
	(*ReadWriteRastoshnoyItem)(nil),     // 8: rastochnoy.ReadWriteRastoshnoyItem
	(*ReadWriteRastochnoyRes)(nil),      // 9: rastochnoy.ReadWriteRastochnoyRes
	(*WriteRastochnoyReq)(nil),          // 10: rastochnoy.WriteRastochnoyReq
	(*WriteRastochnoyRes)(nil),          // 11: rastochnoy.WriteRastochnoyRes
	(*ReadRastochnoyReq)(nil),           // 12: rastochnoy.ReadRastochnoyReq
	(*RastochnoyItem)(nil),              // 13: rastochnoy.RastochnoyItem
	(*ReadRastochnoyRes)(nil),           // 14: rastochnoy.ReadRastochnoyRes
}
var file_protos_rastochnoy_rastoschnoy_proto_depIdxs = []int32{
	0,  // 0: rastochnoy.ReadWriteRastochnoyDB33Res.data:type_name -> rastochnoy.ReadWriteRastoshnoyDB33Item
	8,  // 1: rastochnoy.ReadWriteRastochnoyRes.data:type_name -> rastochnoy.ReadWriteRastoshnoyItem
	13, // 2: rastochnoy.ReadRastochnoyRes.data:type_name -> rastochnoy.RastochnoyItem
	10, // 3: rastochnoy.Rastochnoy.WriteRastochnoy:input_type -> rastochnoy.WriteRastochnoyReq
	7,  // 4: rastochnoy.Rastochnoy.ReadWriteRastochnoy:input_type -> rastochnoy.ReadWriteRastochnoyReq
	12, // 5: rastochnoy.Rastochnoy.ReadRastochnoy:input_type -> rastochnoy.ReadRastochnoyReq
	5,  // 6: rastochnoy.Rastochnoy.WrtieRastochnoy_db37:input_type -> rastochnoy.WrtieRastochnoy_db37Req
	4,  // 7: rastochnoy.Rastochnoy.WriteRastochnoyDB33:input_type -> rastochnoy.WriteRastochnoydb33Req
	2,  // 8: rastochnoy.Rastochnoy.ReadWriteRastochnoyDB33:input_type -> rastochnoy.ReadWriteRastochnoyDB33Req
	11, // 9: rastochnoy.Rastochnoy.WriteRastochnoy:output_type -> rastochnoy.WriteRastochnoyRes
	9,  // 10: rastochnoy.Rastochnoy.ReadWriteRastochnoy:output_type -> rastochnoy.ReadWriteRastochnoyRes
	14, // 11: rastochnoy.Rastochnoy.ReadRastochnoy:output_type -> rastochnoy.ReadRastochnoyRes
	6,  // 12: rastochnoy.Rastochnoy.WrtieRastochnoy_db37:output_type -> rastochnoy.WrtieRastochnoy_db37Res
	3,  // 13: rastochnoy.Rastochnoy.WriteRastochnoyDB33:output_type -> rastochnoy.WriteRastochnoydb33Res
	1,  // 14: rastochnoy.Rastochnoy.ReadWriteRastochnoyDB33:output_type -> rastochnoy.ReadWriteRastochnoyDB33Res
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_rastochnoy_rastoschnoy_proto_init() }
func file_protos_rastochnoy_rastoschnoy_proto_init() {
	if File_protos_rastochnoy_rastoschnoy_proto != nil {
		return
	}
	file_protos_rastochnoy_rastoschnoy_proto_msgTypes[0].OneofWrappers = []any{}
	file_protos_rastochnoy_rastoschnoy_proto_msgTypes[8].OneofWrappers = []any{}
	file_protos_rastochnoy_rastoschnoy_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_rastochnoy_rastoschnoy_proto_rawDesc), len(file_protos_rastochnoy_rastoschnoy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_rastochnoy_rastoschnoy_proto_goTypes,
		DependencyIndexes: file_protos_rastochnoy_rastoschnoy_proto_depIdxs,
		MessageInfos:      file_protos_rastochnoy_rastoschnoy_proto_msgTypes,
	}.Build()
	File_protos_rastochnoy_rastoschnoy_proto = out.File
	file_protos_rastochnoy_rastoschnoy_proto_goTypes = nil
	file_protos_rastochnoy_rastoschnoy_proto_depIdxs = nil
}
