// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: protos/rastochnoy/rastoschnoy.proto

package rastochnoy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rastochnoy_WriteRastochnoy_FullMethodName         = "/rastochnoy.Rastochnoy/WriteRastochnoy"
	Rastochnoy_ReadWriteRastochnoy_FullMethodName     = "/rastochnoy.Rastochnoy/ReadWriteRastochnoy"
	Rastochnoy_ReadRastochnoy_FullMethodName          = "/rastochnoy.Rastochnoy/ReadRastochnoy"
	Rastochnoy_WrtieRastochnoyDb37_FullMethodName     = "/rastochnoy.Rastochnoy/WrtieRastochnoy_db37"
	Rastochnoy_WriteRastochnoyDB33_FullMethodName     = "/rastochnoy.Rastochnoy/WriteRastochnoyDB33"
	Rastochnoy_ReadWriteRastochnoyDB33_FullMethodName = "/rastochnoy.Rastochnoy/ReadWriteRastochnoyDB33"
)

// RastochnoyClient is the client API for Rastochnoy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RastochnoyClient interface {
	WriteRastochnoy(ctx context.Context, in *WriteRastochnoyReq, opts ...grpc.CallOption) (*WriteRastochnoyRes, error)
	ReadWriteRastochnoy(ctx context.Context, in *ReadWriteRastochnoyReq, opts ...grpc.CallOption) (*ReadWriteRastochnoyRes, error)
	ReadRastochnoy(ctx context.Context, in *ReadRastochnoyReq, opts ...grpc.CallOption) (*ReadRastochnoyRes, error)
	WrtieRastochnoyDb37(ctx context.Context, in *WrtieRastochnoyDb37Req, opts ...grpc.CallOption) (*WrtieRastochnoyDb37Res, error)
	WriteRastochnoyDB33(ctx context.Context, in *WriteRastochnoydb33Req, opts ...grpc.CallOption) (*WriteRastochnoydb33Res, error)
	ReadWriteRastochnoyDB33(ctx context.Context, in *ReadWriteRastochnoyDB33Req, opts ...grpc.CallOption) (*ReadWriteRastochnoyDB33Res, error)
}

type rastochnoyClient struct {
	cc grpc.ClientConnInterface
}

func NewRastochnoyClient(cc grpc.ClientConnInterface) RastochnoyClient {
	return &rastochnoyClient{cc}
}

func (c *rastochnoyClient) WriteRastochnoy(ctx context.Context, in *WriteRastochnoyReq, opts ...grpc.CallOption) (*WriteRastochnoyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteRastochnoyRes)
	err := c.cc.Invoke(ctx, Rastochnoy_WriteRastochnoy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rastochnoyClient) ReadWriteRastochnoy(ctx context.Context, in *ReadWriteRastochnoyReq, opts ...grpc.CallOption) (*ReadWriteRastochnoyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadWriteRastochnoyRes)
	err := c.cc.Invoke(ctx, Rastochnoy_ReadWriteRastochnoy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rastochnoyClient) ReadRastochnoy(ctx context.Context, in *ReadRastochnoyReq, opts ...grpc.CallOption) (*ReadRastochnoyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRastochnoyRes)
	err := c.cc.Invoke(ctx, Rastochnoy_ReadRastochnoy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rastochnoyClient) WrtieRastochnoyDb37(ctx context.Context, in *WrtieRastochnoyDb37Req, opts ...grpc.CallOption) (*WrtieRastochnoyDb37Res, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WrtieRastochnoyDb37Res)
	err := c.cc.Invoke(ctx, Rastochnoy_WrtieRastochnoyDb37_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rastochnoyClient) WriteRastochnoyDB33(ctx context.Context, in *WriteRastochnoydb33Req, opts ...grpc.CallOption) (*WriteRastochnoydb33Res, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteRastochnoydb33Res)
	err := c.cc.Invoke(ctx, Rastochnoy_WriteRastochnoyDB33_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rastochnoyClient) ReadWriteRastochnoyDB33(ctx context.Context, in *ReadWriteRastochnoyDB33Req, opts ...grpc.CallOption) (*ReadWriteRastochnoyDB33Res, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadWriteRastochnoyDB33Res)
	err := c.cc.Invoke(ctx, Rastochnoy_ReadWriteRastochnoyDB33_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RastochnoyServer is the server API for Rastochnoy service.
// All implementations must embed UnimplementedRastochnoyServer
// for forward compatibility.
type RastochnoyServer interface {
	WriteRastochnoy(context.Context, *WriteRastochnoyReq) (*WriteRastochnoyRes, error)
	ReadWriteRastochnoy(context.Context, *ReadWriteRastochnoyReq) (*ReadWriteRastochnoyRes, error)
	ReadRastochnoy(context.Context, *ReadRastochnoyReq) (*ReadRastochnoyRes, error)
	WrtieRastochnoyDb37(context.Context, *WrtieRastochnoyDb37Req) (*WrtieRastochnoyDb37Res, error)
	WriteRastochnoyDB33(context.Context, *WriteRastochnoydb33Req) (*WriteRastochnoydb33Res, error)
	ReadWriteRastochnoyDB33(context.Context, *ReadWriteRastochnoyDB33Req) (*ReadWriteRastochnoyDB33Res, error)
	mustEmbedUnimplementedRastochnoyServer()
}

// UnimplementedRastochnoyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRastochnoyServer struct{}

func (UnimplementedRastochnoyServer) WriteRastochnoy(context.Context, *WriteRastochnoyReq) (*WriteRastochnoyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteRastochnoy not implemented")
}
func (UnimplementedRastochnoyServer) ReadWriteRastochnoy(context.Context, *ReadWriteRastochnoyReq) (*ReadWriteRastochnoyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWriteRastochnoy not implemented")
}
func (UnimplementedRastochnoyServer) ReadRastochnoy(context.Context, *ReadRastochnoyReq) (*ReadRastochnoyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadRastochnoy not implemented")
}
func (UnimplementedRastochnoyServer) WrtieRastochnoyDb37(context.Context, *WrtieRastochnoyDb37Req) (*WrtieRastochnoyDb37Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WrtieRastochnoyDb37 not implemented")
}
func (UnimplementedRastochnoyServer) WriteRastochnoyDB33(context.Context, *WriteRastochnoydb33Req) (*WriteRastochnoydb33Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteRastochnoyDB33 not implemented")
}
func (UnimplementedRastochnoyServer) ReadWriteRastochnoyDB33(context.Context, *ReadWriteRastochnoyDB33Req) (*ReadWriteRastochnoyDB33Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWriteRastochnoyDB33 not implemented")
}
func (UnimplementedRastochnoyServer) mustEmbedUnimplementedRastochnoyServer() {}
func (UnimplementedRastochnoyServer) testEmbeddedByValue()                    {}

// UnsafeRastochnoyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RastochnoyServer will
// result in compilation errors.
type UnsafeRastochnoyServer interface {
	mustEmbedUnimplementedRastochnoyServer()
}

func RegisterRastochnoyServer(s grpc.ServiceRegistrar, srv RastochnoyServer) {
	// If the following call pancis, it indicates UnimplementedRastochnoyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rastochnoy_ServiceDesc, srv)
}

func _Rastochnoy_WriteRastochnoy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRastochnoyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).WriteRastochnoy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_WriteRastochnoy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).WriteRastochnoy(ctx, req.(*WriteRastochnoyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rastochnoy_ReadWriteRastochnoy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWriteRastochnoyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).ReadWriteRastochnoy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_ReadWriteRastochnoy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).ReadWriteRastochnoy(ctx, req.(*ReadWriteRastochnoyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rastochnoy_ReadRastochnoy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRastochnoyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).ReadRastochnoy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_ReadRastochnoy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).ReadRastochnoy(ctx, req.(*ReadRastochnoyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rastochnoy_WrtieRastochnoyDb37_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrtieRastochnoyDb37Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).WrtieRastochnoyDb37(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_WrtieRastochnoyDb37_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).WrtieRastochnoyDb37(ctx, req.(*WrtieRastochnoyDb37Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rastochnoy_WriteRastochnoyDB33_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRastochnoydb33Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).WriteRastochnoyDB33(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_WriteRastochnoyDB33_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).WriteRastochnoyDB33(ctx, req.(*WriteRastochnoydb33Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rastochnoy_ReadWriteRastochnoyDB33_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWriteRastochnoyDB33Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RastochnoyServer).ReadWriteRastochnoyDB33(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rastochnoy_ReadWriteRastochnoyDB33_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RastochnoyServer).ReadWriteRastochnoyDB33(ctx, req.(*ReadWriteRastochnoyDB33Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Rastochnoy_ServiceDesc is the grpc.ServiceDesc for Rastochnoy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rastochnoy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rastochnoy.Rastochnoy",
	HandlerType: (*RastochnoyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteRastochnoy",
			Handler:    _Rastochnoy_WriteRastochnoy_Handler,
		},
		{
			MethodName: "ReadWriteRastochnoy",
			Handler:    _Rastochnoy_ReadWriteRastochnoy_Handler,
		},
		{
			MethodName: "ReadRastochnoy",
			Handler:    _Rastochnoy_ReadRastochnoy_Handler,
		},
		{
			MethodName: "WrtieRastochnoy_db37",
			Handler:    _Rastochnoy_WrtieRastochnoyDb37_Handler,
		},
		{
			MethodName: "WriteRastochnoyDB33",
			Handler:    _Rastochnoy_WriteRastochnoyDB33_Handler,
		},
		{
			MethodName: "ReadWriteRastochnoyDB33",
			Handler:    _Rastochnoy_ReadWriteRastochnoyDB33_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/rastochnoy/rastoschnoy.proto",
}
