INSERT INTO rastochnoy_write (key, offsett, value) VALUES
('Boshqarishga_ruxsat', 0.0, false),
('Vibor_L', 0.1, false),
('Vibor_R', 0.2, false),
('Uskareniya_plus', 0.3, false),
('Uskareniya_2xminus', 0.4, false),
('Vibor_X', 0.5, false),
('Vibor_Y', 0.6, false),
('Vibor_Z', 0.7, false),
('Vibor_W', 1.0, false),
('Vibor_V', 1.1, false),
('Vibor_B', 1.2, false),
('Smazka', 1.3, false),
('Gidravlika', 1.4, false),
('Pullt_yuqoriga', 1.5, false),
('Pult_pastga', 1.6, false),
('Svet_on', 1.7, false),
('Shpindel_talchok_plus', 2.0, false),
('Shpindel_talchok_2xminus', 2.1, false),
('Shpindel_rabota_L', 2.2, false),
('Shpindel_rabota_R', 2.3, false),
('Padacha_STOP', 2.4, false),
('SHpindel_STOP', 2.5, false),
('Stupen_1', 2.6, false),
('Stupen_2', 2.7, false),
('Stupen_3', 3.0, false),
('Aloqa_tekshiruvi', 3.1, false)
ON CONFLICT (key) DO NOTHING;
