insert into rastochnoy_read (key, offsett, value) values
('Out_Vibor_L', 0.0, false),
('Out_Vibor_R', 0.1, false),
('Out_Uskareniya+', 0.2, false),
('Out_Uskareniya-', 0.3, false),
('Out_Vibor_X', 0.4, false),
('Out_Vibor_Y', 0.5, false),
('Out_Vibor_Z', 0.6, false),
('Out_Vibor_W', 0.7, false),
('Out_Vibor_V', 1.0, false),
('Out_Vibor_B', 1.1, false),
('Out_Xod_reset', 1.2, false),
('Out_Smazka', 1.3, false),
('Out_Gidravlika', 1.4, false),
('Out_Pullt_yuqoriga', 1.5, false),
('Out_Pult_pastga', 1.6, false),
('Out_Svet_on', 1.7, false),
('Out_Shpindel_talchok+', 2.0, false),
('Out_Shpindel_talchok-', 2.1, false),
('Out_Shpindel_rabota_L', 2.2, false),
('Out_Shpindel_rabota_R', 2.3, false),
('Out_Padacha_STOP', 2.4, false),
('Out_SHpindel_STOP', 2.5, false),
('Out_Stupen_1', 2.6, false),
('Out_Stupen_2', 2.7, false),
('Out_stupen_3', 3.0, false),
('Out_Aloqa_Tekshiruvi', 3.1, false)
on conflict (key) do nothing;
